import ./gen_qabstractscrollarea_types
export gen_qabstractscrollarea_types

type QPlainTextEdit* = object of gen_qabstractscrollarea_types.QAbstractScrollArea
import ../QtGui/gen_qabstracttextdocumentlayout_types
export gen_qabstracttextdocumentlayout_types

type QPlainTextDocumentLayout* = object of gen_qabstracttextdocumentlayout_types.QAbstractTextDocumentLayout
